In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.a = torch.randn(1, 1).requires_grad_(True)
        self.b = torch.randn(1, 1).requires_grad_(True)
        self.s = torch.randn(1, 1).requires_grad_(True)
        
    def forward(self, x):
        return self.a * (x**self.s) + self.b

    def __repr__(self):
        return str(self.a.item()) + "*x^{" + str(self.s.item()) + "} + " + str(self.b.item())

In [56]:
X = torch.rand(1000, 1) * 50 + 1
y = 1.2 * X**2.1 + 4

In [57]:
X[:5], y[:5]

(tensor([[ 3.5801],
         [27.0115],
         [25.5401],
         [31.3364],
         [34.7313]]), tensor([[  21.4726],
         [1221.3992],
         [1086.3038],
         [1666.9720],
         [2067.9260]]))

In [59]:
import torch.optim as optim
net = Net()
# create your optimizer
optimizer = optim.Adam([net.a, net.b, net.s], lr=0.01)
criterion = nn.MSELoss()
best_model = 
for i in range(100000):
    optimizer.zero_grad()   # zero the gradient buffers
    output = net(X)
    loss = criterion(output, y) #+ 0.001 * net.a**2 + 0.01 * net.b**2 + 0.003 * net.s**2
    loss.backward()
    if i % 500 == 0:
        print(net, loss.item())
    optimizer.step()    

-0.5289931893348694*x^{0.07988166809082031} + 1.0962891578674316 3931240.5
2.3126189708709717*x^{1.924354076385498} + 3.139185905456543 5001.82861328125
2.1132264137268066*x^{1.948580026626587} + 2.873189926147461 3658.40380859375
1.8540822267532349*x^{1.9836944341659546} + 2.551608085632324 2101.80029296875
1.583121657371521*x^{2.026047468185425} + 2.244311571121216 811.8675537109375
1.3701958656311035*x^{2.0647246837615967} + 2.0248992443084717 167.38079833984375
1.2579935789108276*x^{2.08758282661438} + 1.922520637512207 15.517849922180176
1.2212111949920654*x^{2.095518112182617} + 1.9017510414123535 1.4083102941513062
1.2139309644699097*x^{2.0971150398254395} + 1.91511869430542 0.9192014336585999
1.2129931449890137*x^{2.0973191261291504} + 1.9404945373535156 0.8914564847946167
1.2127436399459839*x^{2.0973708629608154} + 1.9736430644989014 0.8629500269889832
1.212477207183838*x^{2.097425699234009} + 2.015549421310425 0.827633261680603
1.212143898010254*x^{2.097494125366211} + 2.0681

1.200381875038147*x^{2.0999724864959717} + 3.9841794967651367 0.17287017405033112
1.2001584768295288*x^{2.0999670028686523} + 3.982470989227295 0.0001087376440409571
1.2006747722625732*x^{2.1002557277679443} + 3.9852871894836426 8.987184524536133
1.2001782655715942*x^{2.099964141845703} + 3.9825079441070557 0.0003737310180440545
1.2001334428787231*x^{2.0999786853790283} + 3.9829671382904053 0.0026337727904319763
1.2003470659255981*x^{2.099935293197632} + 3.983790636062622 0.007239732425659895
1.2002390623092651*x^{2.0999503135681152} + 3.983062982559204 0.00041379890171810985
1.2001368999481201*x^{2.099970817565918} + 3.982461452484131 7.546394772361964e-05
1.1994400024414062*x^{2.099097728729248} + 3.983781337738037 57.74939727783203
1.2003185749053955*x^{2.099971055984497} + 3.9833171367645264 0.09012607485055923
1.2002578973770142*x^{2.0999677181243896} + 3.9831809997558594 0.030762070789933205
1.2001391649246216*x^{2.099973201751709} + 3.9826502799987793 0.0004432298883330077
1.200

KeyboardInterrupt: 

In [27]:
y.mean()

tensor(307.6224)

In [97]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.a = (2 * torch.randn(1, 1)).requires_grad_(True)
        self.b = (2 * torch.randn(1, 1)).requires_grad_(True)
        self.s1 = (2 * torch.randn(1, 1)).requires_grad_(True)
        self.s2 = (2 * torch.randn(1, 1)).requires_grad_(True)
        
        
    def forward(self, x):
        return self.a * (x[:, 0]**self.s1) * (x[:, 1]**self.s2) + self.b

    def __repr__(self):
        return ''.join([str(round(self.a.item(), 3)), 
                        "*x^{", str(round(self.s1.item(), 3)), "} * ", 
                        "y^{", str(round(self.s2.item(), 3)), "} + ", 
                        str(self.b.item())])

In [98]:
X = torch.rand(1000, 1) * 50 + 1
Y = torch.rand(1000, 1) * 50 + 1
train = torch.cat([X, Y], 1)
z = 1.3 * X**2 * Y**(-1) + 12

In [99]:
train[:5]


tensor([[16.3335,  4.6578],
        [ 1.4280, 16.1612],
        [12.1116, 38.0939],
        [13.1719, 27.1627],
        [25.0910, 44.3791]])

In [100]:
import torch.optim as optim
net = Net()
# create your optimizer
optimizer = optim.Adam([net.a, net.b, net.s1, net.s2], lr=0.01)
criterion = nn.MSELoss()
for i in range(100000):
    optimizer.zero_grad()   # zero the gradient buffers
    output = net(train)
    loss = criterion(output, y) + 10 * net.a**2 + 10 * net.b**2
    loss.backward()
    if i % 500 == 0:
        print(net, loss.item())
    optimizer.step()    

-2.163*x^{-2.74} * y^{-0.187} + -3.687274217605591 3943312.25
0.031*x^{-3.653} * y^{-1.027} + 1.2721692323684692 3928700.0
0.099*x^{-3.513} * y^{-0.918} + 6.1526360511779785 3914929.75
2.22*x^{0.059} * y^{1.743} + 10.84795093536377 2632911.5
5.575*x^{0.44} * y^{1.141} + 12.579306602478027 2493583.0
8.284*x^{0.541} * y^{0.938} + 14.46911907196045 2443800.75
10.81*x^{0.606} * y^{0.803} + 16.536043167114258 2409018.5
13.301*x^{0.631} * y^{0.721} + 18.747966766357422 2381532.75
15.821*x^{0.627} * y^{0.677} + 21.053001403808594 2358470.75
18.405*x^{0.616} * y^{0.647} + 23.384628295898438 2338435.75
21.077*x^{0.602} * y^{0.623} + 25.664081573486328 2320702.5


KeyboardInterrupt: 

In [ ]:
y.mean()

In [101]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self, a = torch.randn(1, 1).requires_grad_(True), 
                 b = torch.randn(1, 1).requires_grad_(True),
                s = torch.randn(1, 1).requires_grad_(True)):
        super(Net, self).__init__()
        self.a = a
        self.b = b
        self.s = s
        
    def forward(self, x):
        return self.a * (x**self.s) + self.b

    def __repr__(self):
        return str(self.a.item()) + "*x^{" + str(self.s.item()) + "} + " + str(self.b.item())

In [102]:
X = torch.rand(1000, 1) * 50 + 1
y = 1.2 * X**2.1 + 4

In [103]:
X[:5], y[:5]

(tensor([[40.6607],
         [33.2041],
         [39.2492],
         [32.7164],
         [29.4106]]), tensor([[2877.7524],
         [1881.9507],
         [2672.2390],
         [1824.4929],
         [1459.5933]]))

In [105]:
import torch.optim as optim
net = Net()
# create your optimizer
optimizer = optim.Adam([net.a, net.b, net.s], lr=0.01)
criterion = nn.MSELoss()
for i in range(100000):
    optimizer.zero_grad()   # zero the gradient buffers
    output = net(X)
    loss = criterion(output, y) #+ 0.001 * net.a**2 + 0.01 * net.b**2 + 0.003 * net.s**2
    loss.backward()
    if i % 500 == 0:
        print(net, loss.item())
    optimizer.step()    

-0.47959113121032715*x^{-0.48400548100471497} + 0.14454585313796997 4319264.0
2.7631752490997314*x^{1.877172827720642} + 2.1954638957977295 8244.8076171875
2.5149152278900146*x^{1.9024364948272705} + 1.8842211961746216 6377.11181640625
2.177595853805542*x^{1.9410412311553955} + 1.4942528009414673 4016.777587890625
1.7988146543502808*x^{1.9921917915344238} + 1.1009531021118164 1762.1224365234375
1.473905324935913*x^{2.045438289642334} + 0.801784098148346 408.5000915527344
1.2921141386032104*x^{2.0805840492248535} + 0.6564140915870667 38.70995330810547
1.2327325344085693*x^{2.093137264251709} + 0.6278352737426758 3.4141905307769775
1.2216240167617798*x^{2.0955498218536377} + 0.6480336785316467 2.299376964569092
1.220313310623169*x^{2.095832586288452} + 0.6849777102470398 2.238408327102661
1.2199647426605225*x^{2.095904588699341} + 0.7330887317657471 2.173898935317993
1.2195907831192017*x^{2.095980167388916} + 0.7940108180046082 2.0936200618743896
1.2191179990768433*x^{2.096076726913452} 

KeyboardInterrupt: 