In [2]:
import numpy as np
import pandas as pd
from torch.nn import MSELoss
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import copy
from IPython.display import display, Math, Latex

import formula
import functions
import importlib
# from hessian import hessian

In [3]:
importlib.reload(formula)
importlib.reload(functions)

<module 'functions' from '/home/zybinmikhail/Documents/LearningFormulas/functions.py'>

In [4]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [5]:
device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda")

In [6]:
print(functions.descriptive_length_of_fraction(1.0, 3.0))
print(functions.descriptive_length_of_real_number(0.3333333345))

tensor(2.)
tensor(24.9905)


In [7]:
def PrettyRepresent(some_tensor):
    return some_tensor.cpu().numpy()[0].tolist()

In [ ]:
X1 = torch.rand(1000, 1) * 1000
X2 = torch.rand(1000, 1) * 1000
X3 = torch.rand(1000, 1) * 1000
X = torch.cat([X1, X2, X3], dim=1).to(device)
assert X.shape[1] == 3
print(X)

In [0]:
for attempt in range(100):
    print("Attempt", attempt)
    lambd_num = torch.randint(-50, 50, (1, 3)).float().to(device)
    lambd_denom = torch.randint(1, 50, (1, 3)).to(device)
    lambd = lambd_num / lambd_denom
    print(PrettyRepresent(lambd_num), PrettyRepresent(lambd_denom), PrettyRepresent(lambd))
    power_num = torch.randint(-50, 50, (1, 3)).float().to(device)
    power_denom = torch.randint(1, 50, (1, 3)).to(device)
    power = power_num / power_denom
    print(PrettyRepresent(power_num), PrettyRepresent(power_denom), PrettyRepresent(power))
    
    print()
    y = torch.sum(lambd * X**power, 1, keepdim=True)
    # X = X.to(device)
    # y = y.to(device)
    print("Trying Adam")
    formula = LearnFormula(X, y, optimizer_for_formula=optim.Adam, device=device)
    print(formula)
    print(formula.simplify(X, y))
    print("Trying Rprop")
    formula = LearnFormula(X, y, optimizer_for_formula=optim.Rprop, device=device)
    print(formula)
    print(formula.simplify(X, y))
    print("Trying SGD")
    formula = LearnFormula(X, y, optimizer_for_formula=optim.SGD, device=device)
    print(formula)
    print(formula.simplify(X, y))
    print("#####")

tensor([[412.1618, 152.1658, 782.4766],
        [ 86.8828, 297.0470,  75.2827],
        [819.7552, 682.7042, 515.2332],
        ...,
        [353.8344, 825.9497, 272.4909],
        [649.2591, 441.5891, 109.4009],
        [551.4265, 689.8264, 174.8335]], device='cuda:0')
Attempt 0
[-8.0, 7.0, 29.0] [14, 18, 16] [-0.5714285969734192, 0.3888888955116272, 1.8125]
[-41.0, -8.0, 4.0] [8, 32, 25] [-5.125, -0.25, 0.1599999964237213]

Trying Adam
Run #1
Epoch 5000, current loss 12.5, current formula (1.62e-07x_1^{2.57} + 0.145x_2^{-0.218} + 2.57x_3^{-3.53} + 0.143)
Epoch 10000, current loss 11.5, current formula (1.62e-07x_1^{2.57} + 0.147x_2^{-0.216} + 1.73x_3^{-2.5} + 0.147)
Finished run #1, loss 11.507048606872559, best loss 11.507048606872559
Run #2
The model does not seem to converge, finishing at epoch 1000
Finished run #2, loss 2518087680.0, best loss 11.507048606872559
Run #3
Epoch 5000, current loss 1.41, current formula (-1.73x_1^{-5.42} + 1.58x_2^{0.217} + 2.6x_3^{0.059}-4.66)
Epoch 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


Finished run #1, loss 0.0009667888516560197, best loss 0.0009667888516560197
Run #2
Finished run #2, loss 1.3485785075317835e-06, best loss 1.3485785075317835e-06
Run #3
Finished run #3, loss 0.0006471396191045642, best loss 1.3485785075317835e-06
Run #4
Finished run #4, loss 0.016028162091970444, best loss 1.3485785075317835e-06
Run #5
Finished run #5, loss 0.0029740617610514164, best loss 1.3485785075317835e-06
Run #6
Finished run #6, loss 0.0007945856195874512, best loss 1.3485785075317835e-06
Run #7
Finished run #7, loss 0.019250646233558655, best loss 1.3485785075317835e-06
Run #8
Finished run #8, loss 0.022300735116004944, best loss 1.3485785075317835e-06
Run #9
Finished run #9, loss 0.019175121560692787, best loss 1.3485785075317835e-06
Run #10
Finished run #10, loss 0.021744828671216965, best loss 1.3485785075317835e-06
(-0.567x_1^{-5.09} + 0.394x_2^{-0.273} + 1.85x_3^{0.158}-0.0374)
(\frac{-6}{10}x_1^{\frac{-51}{10}} + \frac{4}{10}x_2^{\frac{-3}{10}} + \frac{19}{10}x_3^{\frac{

In [0]:
lambd.cpu().numpy()[0].tolist()

[[-0.7179487347602844, 0.0714285746216774, 4.5]]

In [0]:
formula1 = LearnFormula(X1, y1, optimizer)

In [0]:
simplified_formula1 = formula.simplify(X1, y1, inplace=False)

In [0]:
PrintFormula(simplified_formula1)

In [0]:
formula = LearnFormula(X2, y2)

In [0]:
simplified_formula = formula.simplify(X2, y2, inplace=False)

In [0]:
PrintFormula(simplified_formula)

In [0]:
power.T

tensor([[-1,  0, -2]])

In [16]:
import torch


x = torch.tensor([1.5, 2.5], requires_grad=True)
y = x.pow(2).prod()
h = hessian(y, x, create_graph=True)

print(h)
# tensor([[12.5, 15],
#         [15,  4.5]], grad_fn=<CopySlices>)

h2 = hessian(h.sum(), x)
print(h2)
# tensor([[4, 8],
#         [8, 4]])

tensor([[12.5000, 15.0000],
        [15.0000,  4.5000]], grad_fn=<CopySlices>)
tensor([[4.0000, 8.0000],
        [8.0000, 4.0000]])


In [22]:
X1 = torch.rand(1000, 1) * 1000
X2 = torch.rand(1000, 1) * 1000
X3 = torch.rand(1000, 1) * 1000
X = torch.cat([X1, X2, X3], dim=1).to(device)
assert X.shape[1] == 3
print(X)

lambd_num = torch.randint(-50, 50, (1, 3)).float().to(device)
lambd_denom = torch.randint(1, 50, (1, 3)).to(device)
lambd = lambd_num / lambd_denom
print(PrettyRepresent(lambd_num), PrettyRepresent(lambd_denom), PrettyRepresent(lambd))
power_num = torch.randint(-50, 50, (1, 3)).float().to(device)
power_denom = torch.randint(1, 50, (1, 3)).to(device)
power = power_num / power_denom
print(PrettyRepresent(power_num), PrettyRepresent(power_denom), PrettyRepresent(power))

print()
y = torch.sum(lambd * X**power, 1, keepdim=True)
# X = X.to(device)
# y = y.to(device)
formula = LearnFormula(X, y, optimizer_for_formula=optim.Rprop, device=device)



tensor([[900.0867, 490.2016, 562.9807],
        [426.8015,  82.8674, 137.5523],
        [199.5287, 102.5683, 622.7318],
        ...,
        [134.0636, 224.8117,  88.9737],
        [750.7083, 444.3012, 548.6312],
        [635.8929, 532.0922, 606.6346]])
[-47.0, -47.0, 5.0] [35, 35, 20] [-1.3428571224212646, -1.3428571224212646, 0.25]
[-46.0, -50.0, 11.0] [10, 15, 8] [-4.599999904632568, -3.3333332538604736, 1.375]

Run #1
The model does not seem to converge, finishing at epoch 1000
Finished run #1, loss 87031272.0, best loss 87031272.0
Run #2
The model does not seem to converge, finishing at epoch 1000
Finished run #2, loss 1.900191663163179e+18, best loss 87031272.0
Run #3
The model does not seem to converge, finishing at epoch 1000
Finished run #3, loss 1.9040583706801603e+18, best loss 87031272.0
Run #4
The model does not seem to converge, finishing at epoch 1000
Finished run #4, loss 2056560.125, best loss 2056560.125
Run #5
The model does not seem to converge, finishing at epoch 1

In [23]:
formula

(-5.6x_1^{-4.33} + 11.5x_2^{0.713}-1.96e+03x_3^{-0.414} + 4.53e+02)

In [4]:
from torchcontrib.optim import SWA

...
...

# training loop
base_opt = torch.optim.SGD(model.parameters(), lr=0.1)
opt = torchcontrib.optim.SWA(base_opt, swa_start=10, swa_freq=5, swa_lr=0.05)
for _ in range(100):
     opt.zero_grad()
     loss_fn(model(input), target).backward()
     opt.step()
opt.swap_swa_sgd()

NameError: name 'torch' is not defined

In [3]:
! pip install torchcontrib

  Stored in directory: /home/zybinmikhail/snap/jupyter/6/.cache/pip/wheels/06/06/7b/a5f5920bbf4f12a2c927e438fac17d4cd9560f8336b00e9a99
Successfully built torchcontrib
